### ISSUE TITLE
VSCode Activity Bar extension

### ISSUE THREAD

**Issue by rhysjtevans** [owenfarrell/vscode-vault#4]
It would be great to see v1.1 of this to include an activity bar extension.

If I get any time I'll try and do a poc - although I've not done any vscode work before so might take a while.

**Comment by owenfarrell** [comment]
👋 Hi @rhysjtevans,

Better late then never, I took a stab at doing a UI refresh for this extension. Not being a front-end guru, it took me some time to wrap my head around how to do this correctly. But I think I got there.

Instead of adding it's own element to the activity bar, I added a panel to the existing explorer window. Adding a new element to the activity bar just seemed.... greedy.

If you're willing to experiment, there's an [artifact](https://github.com/owenfarrell/vscode-vault/suites/665817010/artifacts/5922889) posted as a result of my refreshed CI job. I've been using this version on my workstation for a couple days now and really like the update.

Thoughts welcome!
